[cloud_nodes]
ansible-cloud-target ansible_host=143.198.187.54

[cloud_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[cloud_hosts]
ansible-cloud-target ansible_host=143.198.187.54 ansible_user=root

[container_targets]
target-web ansible_host=172.20.10.10
target-db  ansible_host=172.20.10.20

[container_targets:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p root@143.198.187.54"'
